server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # приложение работает на клиентской маршрутизации: любой путь отдаёт index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
